# Generated by Django 4.2.1 on 2023-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Idproducto')),
                ('producto', models.CharField(blank=True, max_length=50, verbose_name='Producto')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
